Name:           ros-indigo-scan-tools
Version:        0.3.2
Release:        0%{?dist}
Summary:        ROS scan_tools package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/scan_tools
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-laser-ortho-projector
Requires:       ros-indigo-laser-scan-matcher
Requires:       ros-indigo-laser-scan-sparsifier
Requires:       ros-indigo-laser-scan-splitter
Requires:       ros-indigo-ncd-parser
Requires:       ros-indigo-polar-scan-matcher
Requires:       ros-indigo-scan-to-cloud-converter
BuildRequires:  ros-indigo-catkin

%description
Laser scan processing tools.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sat Mar 19 2016 Ivan Dryanovski <ccnyroboticslab@gmail.com> - 0.3.2-0
- Autogenerated by Bloom

* Tue Nov 10 2015 Ivan Dryanovski <ccnyroboticslab@gmail.com> - 0.3.0-0
- Autogenerated by Bloom

* Wed Oct 14 2015 Ivan Dryanovski <ccnyroboticslab@gmail.com> - 0.2.1-0
- Autogenerated by Bloom

