Name:           ros-jade-scan-to-cloud-converter
Version:        0.3.1
Release:        0%{?dist}
Summary:        ROS scan_to_cloud_converter package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/laser_scan_matcher
Source0:        %{name}-%{version}.tar.gz

Requires:       pcl
Requires:       pcl-tools
Requires:       ros-jade-pcl-conversions
Requires:       ros-jade-pcl-ros
Requires:       ros-jade-roscpp
BuildRequires:  pcl-devel
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-pcl-conversions
BuildRequires:  ros-jade-pcl-ros
BuildRequires:  ros-jade-roscpp

%description
Converts LaserScan to PointCloud messages.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Mon Dec 21 2015 Ivan Dryanovski <ccnyroboticslab@gmail.com> - 0.3.1-0
- Autogenerated by Bloom

* Sat Oct 17 2015 Ivan Dryanovski <ccnyroboticslab@gmail.com> - 0.2.1-0
- Autogenerated by Bloom

